export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',
}

export const booksConstants = {
    GETALL_BOOKS_REQUEST: 'BOOKS_GETALL_REQUEST',
    GETALL_BOOKS_SUCCESS: 'BOOKS_GETALL_SUCCESS',
    GETALL_BOOKS_FAILURE: 'BOOKS_GETALL_FAILURE',

    ADD_BOOK_REQUEST: 'BOOK_ADD_REQUEST',
    ADD_BOOK_SUCCESS: 'BOOK_ADD_SUCCESS',
    ADD_BOOK_FAILURE: 'BOOK_ADD_FAILURE',
    PATCH_BOOK_REQUEST: 'PATCH_BOOK_REQUEST',
    PATCH_BOOK_SUCCESS: 'PATCH_BOOK_SUCCESS',
    PATCH_BOOK_FAILURE: 'PATCH_BOOK_FAILURE',
    PATCH_CATEGORYBOOKS_REQUEST: 'PATCH_CATEGORYBOOKS_REQUEST',
    PATCH_CATEGORYBOOKS_SUCCESS: 'PATCH_CATEGORYBOOKS_SUCCESS',
    PATCH_CATEGORYBOOKS_FAILURE: 'PATCH_CATEGORYBOOKS_FAILURE',
    DELETE_BOOK_REQUEST: 'DELETE_BOOK_REQUEST',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILURE: 'DELETE_BOOK_FAILURE',

    SET_MENU_ITEM_ID_BOOKS: 'SET_MENU_ITEM_ID_BOOKS',

    GETALL_CATEGORY_BOOKS_REQUEST: 'GETALL_CATEGORY_BOOKS_REQUEST',
    GETALL_CATEGORY_BOOKS_SUCCESS: 'GETALL_CATEGORY_BOOKS_SUCCESS',
    GETALL_CATEGORY_BOOKS_FAILURE: 'GETALL_CATEGORY_BOOKS_FAILURE',

    ADD_CATEGORY_BOOKS_REQUEST: 'ADD_CATEGORY_BOOKS_REQUEST',
    ADD_CATEGORY_BOOKS_SUCCESS: 'ADD_CATEGORY_BOOKS_SUCCESS',
    ADD_CATEGORY_BOOKS_FAILURE: 'ADD_CATEGORY_BOOKS_FAILURE',

    DELETE_CATEGORY_BOOKS_REQUEST: 'DELETE_CATEGORY_BOOKS_REQUEST',
    DELETE_CATEGORY_BOOKS_SUCCESS: 'DELETE_CATEGORY_BOOKS_SUCCESS',
    DELETE_CATEGORY_BOOKS_FAILURE: 'DELETE_CATEGORY_BOOKS_FAILURE',
}

export const postsConstants = {
    GETALL_POSTS_REQUEST: 'GETALL_POSTS_REQUEST',
    GETALL_POSTS_SUCCESS: 'GETALL_POSTS_SUCCESS',
    GETALL_POSTS_FAILURE: 'GETALL_POSTS_FAILURE',

    PATCH_POST_REQUEST: 'PATCH_POST_REQUEST',
    PATCH_POST_SUCCESS: 'PATCH_POST_SUCCESS',
    PATCH_POST_FAILURE: 'PATCH_POST_FAILURE',

    DELETE_POST_REQUEST: 'DELETE_POST_REQUEST',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

    ADD_POST_REQUEST: 'ADD_POST_REQUEST',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
    ADD_POST_FAILURE: 'ADD_POST_FAILURE',
}

export const tasksConstants = {
    GETALL_REQUEST: 'TASKS_GETALL_REQUEST',
    GETALL_SUCCESS: 'TASKS_GETALL_SUCCESS',
    GETALL_FAILURE: 'TASKS_GETALL_FAILURE',
}

export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',
}
